#%RAML 0.8
title: "Norigin Media Mock API"

/auth:
  /anonymous:
    get:
      responses:
        200:
          body:
            application/json:
              example: !include examples/demo/anonymous.json

  /authenticate:
    get:
      responses:
        200:
          body:
            application/json:
              example: !include examples/demo/authenticate.json

/svod:
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/demo/categories-svod.json

/slides:
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/demo/slideshow-home.json

/epg:
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/demo/epg.json

/channel:
  /{channelId}:
    /stream:
      get:
        responses:
          200:
            body:
              binary/octet-stream:
                example: !include examples/demo/channel-stream.example
    /program:
      /{programId}:
        get:
          responses:
            200:
              body:
                application/json:
                  example: !include examples/demo/details-program.json

/vod:
  /{movieId}:
    get:
      responses:
        200:
          body:
            application/json:
              example: !include examples/demo/details-movie.json

    /stream:
      get:
        responses:
          200:
            body:
              binary/octet-stream:
                example: !include examples/demo/movie-stream.example
